import random
num=random.randint(1,6)
if num==1:
    print("(------------)")
    print("(            )")
    print("(            )")
    print("(     O      )")
    print("(            )")
    print("(            )")
    print("(------------)")
    print("You rolled 1")
elif num==2:
    print("(------------)")
    print("(            )")
    print("(            )")
    print("(   O    O   )")
    print("(            )")
    print("(            )")
    print("(------------)")
    print("You rolled 2")
elif num==3:
    print("(------------)")
    print("(         O  )")
    print("(            )")
    print("(     O      )")
    print("(            )")
    print("( O          )")
    print("(------------)")
    print("You rolled 3")
elif num==4:
    print("(------------)")
    print("(            )")
    print("(  O      O  )")
    print("(            )")
    print("(  O      O  )")
    print("(            )")
    print("(------------)")
    print("You rolled 4")
elif num==5:
    print("(------------)")
    print("(  O       O )")
    print("(            )")
    print("(      O     )")
    print("(            )")
    print("(  O       O )")
    print("(------------)")
    print("You rolled 5")
elif num==6:
    print("(------------)")
    print("(            )")
    print("(   O    O   )")
    print("(   O    O   )")
    print("(   O    O   )")
    print("(            )")
    print("(------------)")
    print("You rolled 6")